---
title: "2_reproduce_paper_code"
---

# Load libraries
```{r}
library(dplyr)
library(tidyr)
library(readr)
library(GenomicRanges)
library(reshape2)
library(openxlsx)
library(ggplot2)
library(Matrix)
library(EpiTrace)
library(Seurat)
library(SeuratObject)
library(ggtree)
library(EnsDb.Hsapiens.v86)
library(patchwork)
library(ArchR)
library(Signac)
library(ggbeeswarm)
library(ggthemes)
library(ggsci)
library(ggpubr)
library(pheatmap)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(ChIPseeker)
library(ComplexHeatmap)
library(zoo)
library(RColorBrewer)
library(openxlsx)
library(WGCNA)
library(parallel)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(ComplexHeatmap)
library(circlize)

options(bitmapType='cairo') # solve the PNG/X11 issue
data("clock_gr_list")
```


# Running paper sample 
```{r}
path = '/projectnb/ds596/projects/Team 3/paper_code'

# build Epitrace object 
load(file.path(path, 'Packed_Figure_Reproducibility/input_data_for_EpiTrace/Figure8/matrix/GBM_GSM4131779.testdata.RData')) # this is hg38
annotations <- readRDS(file.path(path,'Packed_Figure_Reproducibility/input_data_for_EpiTrace/Figure8/meta/get_GR_from_EnsDb_hm_v86.rds'))

GBM_GSM4131779$GR -> peakset
initiated_peaks <- Init_Peakset(peakset) 
initiated_mm <- Init_Matrix(cellname = colnames(GBM_GSM4131779$MM),peakname = gsub('_','-',rownames(GBM_GSM4131779$MM)),matrix = GBM_GSM4131779$MM)

epitrace_obj <- EpiTrace_prepare_object(initiated_peaks,initiated_mm,ref_genome = 'hg38',non_standard_clock = F,clock_gr_list = clock_gr_list,qualnum=1)
DefaultAssay(epitrace_obj) <- 'peaks' 
epitrace_obj <- epitrace_obj %>% Signac::RunTFIDF() %>% Signac::FindTopFeatures(min.cutoff=50) %>% Signac::RunSVD() %>% RunUMAP(reduction = 'lsi', dims = 2:31) %>% FindNeighbors(reduction = 'lsi', dims = 2:31,k.param = 21) %>% FindClusters(verbose = FALSE, algorithm = 3,resolution = 0.8)
# epitrace_obj_backup <- epitrace_obj
epitrace_obj2 <- subset(epitrace_obj,seurat_clusters %ni% c('2','8'))

epitrace_obj_age_estimated <- RunEpiTraceAge(epitrace_obj2, normalization_method = 'randomized' )


# Figure 8a
colors_plot <- colorRampPalette(colors=RColorBrewer::brewer.pal(n=9,name = 'Set1'))(length(unique(epitrace_obj_age_estimated$seurat_clusters)))
names(colors_plot) <- unique(epitrace_obj_age_estimated$seurat_clusters)

DimPlot(epitrace_obj_age_estimated,label = T)  -> p1
p1$data %>% dplyr::group_by(ident) %>% dplyr::summarise(umap_1=mean(umap_1),umap_2=mean(umap_2)) -> p1_loc
ggplot(p1$data,aes(x=umap_1,y=umap_2,color=ident)) + geom_point() + theme_classic() + scale_color_manual(values = colors_plot) + theme(legend.position = 'none') -> p1

pdf("./Packed_Figure_Reproducibility/Plots/Figure8a_GBM_UMAP.pdf", width = 8,height = 6)
p1 + geom_label(data=p1_loc,mapping=aes(x=umap_1,y=umap_2,label=ident),fill='white',color='black')
dev.off()

```



```{r}
# Figure 8b to 8e
target_genes <- c('MDM4','EGFR','PDGFRA')
granges(epitrace_obj_age_estimated) -> tempdf_GR
lapply(target_genes,function(x){
  if(x %in% 'PDGFRA'){
    widthid = 10000
  }else{
    widthid = 300
  }
  tempdf_GR[findOverlaps(tempdf_GR,flank(annotations[annotations$gene_name %in% x,],width=widthid,both=T))@from %>% unique,] -> testdf
  testdf$gene <- x
  testdf <- as.data.frame(testdf)
  testdf
}) %>% bind_rows -> testdf 
testdf$target_feature <- paste0(testdf$seqnames,'-',testdf$start,'-',testdf$end)
lapply(target_genes,function(x){
  testdf$target_feature[testdf$gene %in% x]
}) -> featurelist 
names(featurelist) <- target_genes

Seurat::AddModuleScore(epitrace_obj_age_estimated,features = featurelist) -> epitrace_obj_age_estimated
colnames(epitrace_obj_age_estimated@meta.data)[((ncol(epitrace_obj_age_estimated@meta.data)-2):ncol(epitrace_obj_age_estimated@meta.data))] <- target_genes

FeaturePlot(epitrace_obj_age_estimated,features = c('EpiTraceAge_AllClock',target_genes),order = T,ncol = 4,combine = F) -> gene_plot_list 

epitrace_obj_age_estimated@meta.data$seurat_clusters <- factor(epitrace_obj_age_estimated@meta.data$seurat_clusters, levels = rev(c(3,0,5,6,4,7,9,1)))

color_use <- c('coral','chartreuse4','cornflowerblue','red')

lapply(1:length(gene_plot_list),function(idx){
  gene_plot_list[[idx]]$data -> pdata 
  gene_plot_list[[idx]]$labels$title -> ptitle
  if(idx==1){
    ptitle <- 'Clock'
  }
  if(idx==1){
    xlabel <- 'EpiTrace Age'
  }else{
    xlabel <- 'Expression'
  }
  pdata$newvalue <- pdata$value <- pdata[,ncol(pdata)]
  pdata$ident <- factor(pdata$ident,levels=levels(epitrace_obj_age_estimated@meta.data$seurat_clusters),ordered = T)
  ggplot(pdata,aes(x=value,y=ident,fill=ident,group=ident)) + geom_violin(aes(fill=ident),scale='width') + theme_classic() + scale_fill_manual(values = colors_plot) +geom_boxplot(fill='black',width=0.2,outlier.alpha = 0) + theme(legend.position = 'none',axis.title.y = element_blank(),axis.text.x=element_blank(),text=element_text(size=20)) + ggtitle(ptitle) + xlab(xlabel)
}) -> final_gene_exp_violin_list  

wrap_plots(final_gene_exp_violin_list,ncol=2) -> p2

# pdf("./Packed_Figure_Reproducibility/Plots/Figure8b_8e_GBM_expression.pdf", width = 6,height = 6)
# p2
# dev.off()

# Figure 8f
epitrace_obj_age_estimated@meta.data -> prepare_data_meta
prepare_data_meta$label <- prepare_data_meta$seurat_clusters
prepare_data_meta %>% dplyr::group_by(label) %>% dplyr::summarise(Normal=sum(EpiTraceAge_MitosisClock<0.3),MDM4_amp=sum(MDM4>-0.1),EGFR=sum(EGFR>0 ),PDGFRA=sum(PDGFRA>0.05),n=n())

prepare_data_meta%>%dplyr::select(EpiTraceAge_MitosisClock,MDM4,PDGFRA,EGFR) %>% dist %>% hclust() %>% cutree(5) -> prepare_data_meta$hdist_class

prepare_data_meta$manual_class <- 'Normal'
prepare_data_meta$manual_class[prepare_data_meta$MDM4 > -0.1] <- 'MDM4+'
prepare_data_meta$manual_class[prepare_data_meta$EGFR > 0 & prepare_data_meta$MDM4 > -0.1] <- 'EGFR+'
prepare_data_meta$manual_class[prepare_data_meta$PDGFRA > 0.1 & prepare_data_meta$MDM4 > -0.1] <- 'PDGFRA+'
prepare_data_meta$manual_class[prepare_data_meta$PDGFRA > 0.1 & prepare_data_meta$EGFR > 0 & prepare_data_meta$MDM4 > -0.1] <- 'EGFR+ PDGFRA+'

prepare_data_meta$manual_class <- factor(prepare_data_meta$manual_class,levels=c('Normal','MDM4+','EGFR+ PDGFRA+','EGFR+','PDGFRA+'))

colors_pie = c('Normal'='white','MDM4+'='gray','EGFR+ PDGFRA+'='orange','EGFR+'='red','PDGFRA+'='black')

pdf("./Packed_Figure_Reproducibility/Plots/Figure8f_GBM_EpiTrace_Age_in_different_celltypes.pdf", width = 7,height = 3.5)
ggplot(prepare_data_meta,aes(x=EpiTraceAge_MitosisClock,y=manual_class)) + geom_violin(aes(fill=manual_class),scale='width') + theme_classic() + geom_boxplot(fill='darkgray',outlier.alpha = 0,width=0.1) + scale_fill_manual(values=colors_pie) + theme(axis.title.y = element_blank(),text=element_text(size=15)) + xlab('MitosisClock')
dev.off()

# Figure 8g , tree
phylotree_res <- RunEpiTracePhylogeny(epitrace_obj_age_estimated,run_reduction = T)
phylotree_res[[4]][[2]] -> data.tree_clock
data.tree_clock <- ape::root(data.tree_clock,outgroup='1')
colors_plot <- colorRampPalette(colors=RColorBrewer::brewer.pal(n=9,name = 'Set1'))(length(unique(epitrace_obj_age_estimated$seurat_clusters)))
names(colors_plot) <- unique(epitrace_obj_age_estimated$seurat_clusters)

colors_plot <- colorRampPalette(colors=RColorBrewer::brewer.pal(n=9,name = 'Set1'))(length(unique(prepare_data_meta$seurat_clusters)))
names(colors_plot) <- unique(prepare_data_meta$seurat_clusters)
colors_pie = c('Normal'='white','MDM4+'='gray','EGFR+ PDGFRA+'='orange','EGFR+'='red','PDGFRA+'='black')

p2_tree <- ggtree::ggtree(data.tree_clock,layout='rectangular',ladderize = FALSE)  + geom_tippoint(aes(color = label),size=5) + scale_color_manual(values = colors_plot) + geom_tiplab(color='black',size=10,offset=10) + theme(legend.position='none')

pdf("./Packed_Figure_Reproducibility/Plots/Figure8g_GBM_clock_phylo.pdf", width = 7,height = 4)
p2_tree
dev.off()
```


# Doing all data 


```{r}
# Batch processing for all samples (each in its own output folder)
data_dir <- '/projectnb/ds596/projects/Team 3/data/GSE139136'
main_output_dir <- '/projectnb/ds596/students/preshita/processed_data/all_gbm'
dir.create(main_output_dir, showWarnings = FALSE, recursive = TRUE)

# Load annotation (assume same for all samples)
annotation_path <- '/projectnb/ds596/projects/Team 3/paper_code/Packed_Figure_Reproducibility/input_data_for_EpiTrace/Figure8/meta/get_GR_from_EnsDb_hm_v86.rds'
annotations <- readRDS(annotation_path)

# Helper to get sample prefixes
all_files <- list.files(data_dir, pattern = '_matrix.mtx.gz$', full.names = FALSE)
sample_prefixes <- gsub('_matrix.mtx.gz', '', all_files)

sample_prefixes
```

"GSM4131776_4218" "GSM4131777_4250" "GSM4131778_4275" "GSM4131779_4349"

```{r}

sample = "GSM4131776_4218"

for (sample in sample_prefixes) {
  cat('Processing', sample, '\n')
  matrix_file <- file.path(data_dir, paste0(sample, '_matrix.mtx.gz'))
  peaks_file <- file.path(data_dir, paste0(sample, '_peaks.bed.gz'))
  barcodes_file <- file.path(data_dir, paste0(sample, '_barcodes.tsv.gz'))

  # Create output subfolder for this sample
  sample_output_dir <- file.path(main_output_dir, sample)
  dir.create(sample_output_dir, showWarnings = FALSE, recursive = TRUE)

  # Load data
  mat <- Matrix::readMM(matrix_file)
  peaks <- readr::read_tsv(peaks_file, col_names = FALSE)
  barcodes <- readr::read_tsv(barcodes_file, col_names = FALSE)
  rownames(mat) <- paste0(peaks$X1, '-', peaks$X2, '-', peaks$X3)
  colnames(mat) <- barcodes$X1

  # Build Epitrace object
  peakset <- GenomicRanges::GRanges(seqnames = peaks$X1, ranges = IRanges::IRanges(start = peaks$X2, end = peaks$X3))
  initiated_peaks <- Init_Peakset(peakset)
  initiated_mm <- Init_Matrix(cellname = colnames(mat), peakname = rownames(mat), matrix = mat)
  epitrace_obj <- EpiTrace_prepare_object(initiated_peaks, initiated_mm, ref_genome = 'hg38', non_standard_clock = FALSE, clock_gr_list = clock_gr_list, qualnum = 1)
  DefaultAssay(epitrace_obj) <- 'peaks'
  epitrace_obj <- epitrace_obj %>% Signac::RunTFIDF() %>% Signac::FindTopFeatures(min.cutoff = 50) %>% Signac::RunSVD() %>% RunUMAP(reduction = 'lsi', dims = 2:31) %>% FindNeighbors(reduction = 'lsi', dims = 2:31, k.param = 21) %>% FindClusters(verbose = FALSE, algorithm = 3, resolution = 0.8)

  # # Dynamically exclude clusters if they exist in this sample
  # clusters_to_exclude <- intersect(c('2', '8'), unique(as.character(epitrace_obj$seurat_clusters)))
  # if (length(clusters_to_exclude) > 0) {
  #   epitrace_obj2 <- subset(epitrace_obj, !(seurat_clusters %in% clusters_to_exclude))
  # } else {
  #   epitrace_obj2 <- epitrace_obj
  # }

  # Downstream analysis (as before, but save with sample-specific names)
  epitrace_obj_age_estimated <- RunEpiTraceAge(epitrace_obj, normalization_method = 'randomized')

  num_cat = length(unique(epitrace_obj_age_estimated$seurat_clusters))
  # Figure 8a
  colors_plot <- colorRampPalette(colors = RColorBrewer::brewer.pal(n = num_cat, name = 'Set3'))(num_cat)
  names(colors_plot) <- unique(epitrace_obj_age_estimated$seurat_clusters)
  DimPlot(epitrace_obj_age_estimated, label = T)  -> p1
  p1$data %>% dplyr::group_by(ident) %>% dplyr::summarise(umap_1 = mean(umap_1), umap_2 = mean(umap_2)) -> p1_loc
  ggplot(p1$data, aes(x = umap_1, y = umap_2, color = ident)) + geom_point() + theme_classic() + scale_color_manual(values = colors_plot) + theme(legend.position = 'none') -> p1
  pdf(file.path(sample_output_dir, 'Figure8a_UMAP.pdf'), width = 8, height = 6)
  print(p1 + geom_label(data = p1_loc, mapping = aes(x = umap_1, y = umap_2, label = ident), fill = 'white', color = 'black'))
  dev.off()

  # Figure 8b-8e
  target_genes <- c('MDM4', 'EGFR', 'PDGFRA')
  granges(epitrace_obj_age_estimated) -> tempdf_GR
lapply(target_genes, function(x) {
  if (x %in% 'PDGFRA') {
    widthid = 10000
  } else {
    widthid = 300
  }
  
  testdf <- tempdf_GR[findOverlaps(tempdf_GR, flank(annotations[annotations$gene_name %in% x, ], width = widthid, both = T))@from %>% unique, ]
  
  # Check if GRanges has elements
  if (length(testdf) > 0) {
    testdf$gene <- x
    testdf <- as.data.frame(testdf)
    testdf
  } else {
    NULL
  }
}) %>% bind_rows -> testdf
  
testdf$target_feature <- paste0(testdf$seqnames, '-', testdf$start, '-', testdf$end)
  lapply(target_genes, function(x) {
    testdf$target_feature[testdf$gene %in% x]
  }) -> featurelist
  names(featurelist) <- target_genes
  
  
# Filter out empty lists
featurelist <- featurelist[sapply(featurelist, length) > 0]

# Check which genes were removed
removed_genes <- target_genes[!(target_genes %in% names(featurelist))]
if (length(removed_genes) > 0) {
  message("Genes removed (no features found): ", paste(removed_genes, collapse = ", "))
}

# Now run AddModuleScore

  
  Seurat::AddModuleScore(epitrace_obj_age_estimated, features = featurelist) -> epitrace_obj_age_estimated
  colnames(epitrace_obj_age_estimated@meta.data)[((ncol(epitrace_obj_age_estimated@meta.data) - 2):ncol(epitrace_obj_age_estimated@meta.data))] <- target_genes
  FeaturePlot(epitrace_obj_age_estimated, features = c('EpiTraceAge_AllClock', target_genes), order = T, ncol = 4, combine = F) -> gene_plot_list
  epitrace_obj_age_estimated@meta.data$seurat_clusters <- factor(epitrace_obj_age_estimated@meta.data$seurat_clusters, levels = rev(sort(unique(epitrace_obj_age_estimated@meta.data$seurat_clusters))))
  color_use <- c('coral', 'chartreuse4', 'cornflowerblue', 'red')
  lapply(1:length(gene_plot_list), function(idx) {
    gene_plot_list[[idx]]$data -> pdata
    gene_plot_list[[idx]]$labels$title -> ptitle
    if (idx == 1) {
      ptitle <- 'Clock'
      xlabel <- 'EpiTrace Age'
    } else {
      xlabel <- 'Expression'
    }
    pdata$newvalue <- pdata$value <- pdata[, ncol(pdata)]
    pdata$ident <- factor(pdata$ident, levels = levels(epitrace_obj_age_estimated@meta.data$seurat_clusters), ordered = T)
    ggplot(pdata, aes(x = value, y = ident, fill = ident, group = ident)) +
      geom_violin(aes(fill = ident), scale = 'width') +
      theme_classic() +
      scale_fill_manual(values = colors_plot) +
      geom_boxplot(fill = 'black', width = 0.2, outlier.alpha = 0) +
      theme(legend.position = 'none', axis.title.y = element_blank(), axis.text.x = element_blank(), text = element_text(size = 20)) +
      ggtitle(ptitle) + xlab(xlabel)
  }) -> final_gene_exp_violin_list
  wrap_plots(final_gene_exp_violin_list, ncol = 2) -> p2
  pdf(file.path(sample_output_dir, 'Figure8b_8e_expression.pdf'), width = 6, height = 6)
  print(p2)
  dev.off()

  # Figure 8f
  prepare_data_meta <- epitrace_obj_age_estimated@meta.data
  prepare_data_meta$label <- prepare_data_meta$seurat_clusters
  prepare_data_meta %>% dplyr::group_by(label) %>% dplyr::summarise(Normal = sum(EpiTraceAge_MitosisClock < 0.3), MDM4_amp = sum(MDM4 > -0.1), EGFR = sum(EGFR > 0), PDGFRA = sum(PDGFRA > 0.05), n = n())
  prepare_data_meta %>% dplyr::select(EpiTraceAge_MitosisClock, MDM4, PDGFRA, EGFR) %>% dist %>% hclust() %>% cutree(5) -> prepare_data_meta$hdist_class
  prepare_data_meta$manual_class <- 'Normal'
  prepare_data_meta$manual_class[prepare_data_meta$MDM4 > -0.1] <- 'MDM4+'
  prepare_data_meta$manual_class[prepare_data_meta$EGFR > 0 & prepare_data_meta$MDM4 > -0.1] <- 'EGFR+'
  prepare_data_meta$manual_class[prepare_data_meta$PDGFRA > 0.1 & prepare_data_meta$MDM4 > -0.1] <- 'PDGFRA+'
  prepare_data_meta$manual_class[prepare_data_meta$PDGFRA > 0.1 & prepare_data_meta$EGFR > 0 & prepare_data_meta$MDM4 > -0.1] <- 'EGFR+ PDGFRA+'
  prepare_data_meta$manual_class <- factor(prepare_data_meta$manual_class, levels = c('Normal', 'MDM4+', 'EGFR+ PDGFRA+', 'EGFR+', 'PDGFRA+'))
  colors_pie = c('Normal' = 'white', 'MDM4+' = 'gray', 'EGFR+ PDGFRA+' = 'orange', 'EGFR+' = 'red', 'PDGFRA+' = 'black')
  pdf(file.path(sample_output_dir, 'Figure8f_EpiTrace_Age_in_celltypes.pdf'), width = 7, height = 3.5)
  print(ggplot(prepare_data_meta, aes(x = EpiTraceAge_MitosisClock, y = manual_class)) +
          geom_violin(aes(fill = manual_class), scale = 'width') +
          theme_classic() +
          geom_boxplot(fill = 'darkgray', outlier.alpha = 0, width = 0.1) +
          scale_fill_manual(values = colors_pie) +
          theme(axis.title.y = element_blank(), text = element_text(size = 15)) +
          xlab('MitosisClock'))
  dev.off()

  saveRDS(epitrace_obj_age_estimated, file.path(sample_output_dir, 'epitrace_obj_age_estimated.rds'))
  
  # # Figure 8g, tree
  # phylotree_res <- RunEpiTracePhylogeny(epitrace_obj_age_estimated, run_reduction = T)
  # phylotree_res[[4]][[2]] -> data.tree_clock
  # data.tree_clock <- ape::root(data.tree_clock, outgroup = '1')
  # colors_plot <- colorRampPalette(colors = RColorBrewer::brewer.pal(n = num_cat, name = 'Set3'))(num_cat)
  # names(colors_plot) <- unique(epitrace_obj_age_estimated$seurat_clusters)
  # colors_plot <- colorRampPalette(colors = RColorBrewer::brewer.pal(n = num_cat, name = 'Set3'))(num_cat)
  # names(colors_plot) <- unique(prepare_data_meta$seurat_clusters)
  # colors_pie = c('Normal' = 'white', 'MDM4+' = 'gray', 'EGFR+ PDGFRA+' = 'orange', 'EGFR+' = 'red', 'PDGFRA+' = 'black')
  # p2_tree <- ggtree::ggtree(data.tree_clock, layout = 'rectangular', ladderize = FALSE) +
  #   geom_tippoint(aes(color = label), size = 5) +
  #   scale_color_manual(values = colors_plot) +
  #   geom_tiplab(color = 'black', size = 10, offset = 10) +
  #   theme(legend.position = 'none')
  # pdf(file.path(sample_output_dir, 'Figure8g_clock_phylo.pdf'), width = 7, height = 4)
  # print(p2_tree)
  # dev.off()
}

```